import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import Navbar from "@/components/navbar/navbar";
import Footer from "@/components/footer/Footer";
import Navbar from "@/components/navbar/navbar";
import { GlobalContextProvider } from "@/components/context/globalContext";
import { ConvexProvider } from "@/components/providers/ConvexProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="overflow-x-hidden">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden`}
      >
        <div className="w-full overflow-x-hidden">
          <ConvexProvider>
            <GlobalContextProvider>
              <Navbar />
              {children}
              <Footer />
            </GlobalContextProvider>
          </ConvexProvider>
        </div>
      </body>
    </html>
  );
}
